[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "open-dcoder"
dynamic = ["dependencies", "optional-dependencies"]
version = "0.1.0"
authors = [
  { name="Fred Z. Peng", email="zp70@duke.edu" },
]
description = "Open-dCoder: Open Diffusion Large Language Model for Code Generation"
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["diffusion", "language model", "code generation", "machine learning", "pytorch"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Code Generators",
]

[project.urls]
Homepage = "https://github.com/pengzhangzhi/dLLM-training"
Issues = "https://github.com/pengzhangzhi/dLLM-training/issues"
Repository = "https://github.com/pengzhangzhi/dLLM-training"

[tool.ruff]
target-version = "py38"
line-length = 119
indent-width = 4

[tool.ruff.lint]
ignore = ["C901", "E501", "E741", "W605", "C408"]
select = ["C", "E", "F", "I", "W"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["veomni"]
known-third-party = ["torch", "transformers", "wandb"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# pyproject.toml

[tool.mypy]
# Mypy will not check files in these directories
exclude = [
    'lm-evaluation-harness/',
    'veomni/',
    'human-eval-infilling/',
]
